
spring:
  application:
    name: ecomap
  datasource:
    url: jdbc:postgresql://localhost:5432/ecomap
    username: postgres
    password: Maestro_1337
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
        jdbc:
          batch_size: 10
        order_updates: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true

  sql:
    init:
      mode: always